### PR TITLE
Uploading All America Micromouse Competition (AAMC) Maze Files

### PR DESCRIPTION
**Pull request by aloeveratheplant**
Uploading All America Micromouse Competition (AAMC Files) as hosted at UCLA from the IEEE at UCLA maze bank. File format is different than those of the original repository as the format followed was for this (https://github.com/mackorone/mms) maze solving simulator used in our program, but can be manually updated as needed to fit the rest of the repository. All of these mazes are classic sized, with start boxes at the bottom left corner, and the middle 4 boxes as the goal.

Please feel free to reach out, I am the head maze designer for AAMC 2023 and 2024, and would be glad to talk about all things Micromouse including the program at UCLA :)

### CODE REVIEW

**Comment by micromouseonline** [comment]
Thank you for your contribution.

I woul love it if you could edit these up to be consistent with the other files in the collection - just to save me the effort later..

Did you come along to the APEC contest at Long Beach this year?  We tried to get in touch but could not seem to find a good contact.

**Comment by aloeveratheplant** [comment]
Sorry for the late reply! I'll work on updating the files to match the formatting in the collection at a later time (hopefully a few days) and update the pull request. I was not personally at APEC this year, but I know that a team of people from our Micromouse was present. I can redirect you to a more permanent contact as we are currently in our transitionary phase to next year's Micromouse Project Leads at UCLA.

**Comment by aloeveratheplant** [comment]
Hi, Sorry for the delay and if I'm poorly navigating GitHub, the files should be updated to the correct format now.

**Comment by micromouseonline** [comment]
thank you

**Pull request merged**
