### PR TITLE
Add Micromouse Portuguese Contest 2019 mazes (FINAL A is the hard one)

### PR DESCRIPTION
**Pull request by Peque**

### CODE REVIEW

**Review by micromouseonline — APPROVED** [review]

**Comment by Peque** [comment]
@micromouseonline Want me to change the commit subject? I can change the names too to `-final-hard` and `final-easy`. :joy:

**Comment by micromouseonline** [comment]
Yes. Maybe some other name that distiguishes them. -final-expert and -final-novice?

The -a and -b makes it seem the wrong way round for the order they came in.

On 1 May 2019 00:20:31 BST, "Miguel Sánchez de León Peque" <notifications@github.com> wrote:
>@micromouseonline Want me to change the commit subject? I can change
>the names too to `-final-hard` and `final-easy`. :joy:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/micromouseonline/mazefiles/pull/15#issuecomment-488149606

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Peque** [comment]
@micromouseonline Force-pushed the changes. I like it better with the new naming. :+1:

**Comment by micromouseonline** [comment]
Thank you

—
Peter Harrison
peter.harrison@helicron.net

**Pull request merged**
