### PR TITLE
Oshwdem2019.txt

### PR DESCRIPTION
**Pull request by Menyiques**

### CODE REVIEW

**Comment by Peque** [comment]
Looks good! :blush: 

@micromouseonline Why pipelines for merge requests are not being triggered is still a mistery. :woman_shrugging:

**Comment by micromouseonline** [comment]
@Menyiques - Thank you.

When and where was this maze used?  I will add that to the commit message.

**Comment by Menyiques** [comment]
Used on Micromouse labyrinth competition Oshwdem 2019 on 09/Nov/2019
La Coruña, Spain
https://oshwdem.org/2019/05/oshwdem-2019/
Thanks

**Comment by micromouseonline** [comment]
Now what is Travis bleating about?

—
Peter Harrison
peter.harrison@helicron.net

**Pull request merged**
